### ISSUE TITLE
Any reason to use z-index?

### ISSUE THREAD

**Issue by shirshak55** [deulos/vue-flux#22]
Thank you. But is there any reason to use z-index? Many people will face problem due to z-index issue like navigation bar popup will be hidden due to slider and z-index don't work on so many thing so it may be hard to make navigation bar appear front of text.

Thanks

**Comment by deulos** [comment]
Sure, the slider transitions need the z-index to be displayed properly, plus the flux components in order to be displayed over. So it is a must and transitions won't work without it.

Transitions use a variable number of pieces and each one will increase z-index + 1.

Anyway if you notice the z-index values are pretty low to avoid conflicts, so you can use any z-index value over 100 (which is the z-index used in flux components) in your navigation bar and will be displayed properly.

**Comment by deulos** [comment]
No, its not possible to use negative, the images has position absolute so they would not show.

For the floats just add `position: relative` and z-index will work, although I recommend you to use flex for the layout.

**Comment by shirshak55** [comment]
@deulos yea will use css grid and flex now. It was old styles so :)
