### ISSUE TITLE
How can I make image with background-size: contain

### ISSUE THREAD

**Issue by stpham-net** [deulos/vue-flux#42]
I have some image have height is greater than width but I need show full image in slide then can do it with css property `background-size: contain`, but I don't see any option in vue-flux for that.

Is possible to show full image height is greater than width and custom color of background behind the image?

Example:

![screenshot_4](https://user-images.githubusercontent.com/12744590/51436837-2f59e180-1cc7-11e9-8c5e-421a9babb986.png)

Or something like this is cool:

![screenshot_1](https://user-images.githubusercontent.com/12744590/51436896-dcccf500-1cc7-11e9-8b78-0351a93f0ca8.png)

**Comment by deulos** [comment]
It is not possible. The reason is because doing so, would make transitions look wrong.

At the very first versions I had it like this and had to remove because screwed the effect.

The only thing you can do is to set all images with same height and width, set that size to the slider in the middle and control the parent node background the way you want.

Regards

**Comment by stpham-net** [comment]
Thank @deulos!
