### ISSUE TITLE
Parallax mobile fixed

### ISSUE THREAD

**Issue by nodeskipper** [deulos/vue-flux#47]
Hello, 

Not really an issue, but more an advice demand:

How to get in FluxParallax the 'fixed' component (third section) to work on mobile? Anyone solved this?

**Comment by deulos** [comment]
Hello, that is caused because chrome on mobile has a bug with the style backgroundSize: cover

If it is not solved on the release of vue-flux 6.0 I will add a workaround.

Meanwhile you can find some solutions here: https://stackoverflow.com/questions/14876035/background-size-cover-not-working-in-portrait-on-android-tablet

**Comment by nodeskipper** [comment]
Thanks a lot Deulos, 

I will try to try. If I get something useful, I will post it here for others, otherwise I will wait for the 6.0 :)

Thanks

**Comment by deulos** [comment]
This is fixed in version beta.18 that I just released :)

**Comment by deulos** [comment]
Looks like the fix is not working on IOS so I will reopen this and find another.

**Comment by deulos** [comment]
I have been looking to find a workaround but looks like it is not possible in IOS, and that they consider it a "FEATURE"

So this will not be fixed in IOS until they allow so.

Regards!
