### ISSUE TITLE
Suggestion: vh height option for FluxParallax

### ISSUE THREAD

**Issue by shubhra14** [deulos/vue-flux#55]
Would love to have an option to be able to set height of the FluxParallax component in vh. Thank you :)

**Comment by deulos** [comment]
Hello, this is already implemented in the source code of the FluxParallax but didn't release a new beta with this changes because I still need to fix the holder parameter. I expect to have it published today or tomorrow.

The update removes the height parameter, fixes the chrome mobile bug, reduces its size, fixes holder element and improves performance.

**Comment by deulos** [comment]
Check last beta.18 version :)
