### ISSUE TITLE
Thumbnails of photos

### ISSUE THREAD

**Issue by BorysTyminski** [deulos/vue-flux#9]
Last thing I can think of to improve is to create option of showing thumbnails below the slider.

I'm creating estate agency page and on single offer page I would like to show slider (except that I'm using slider on first page as background of first view) with thumbnails so it would like similiar to this

![image](https://user-images.githubusercontent.com/40339232/44853971-a4b90d00-ac67-11e8-9eaa-aef1e8516719.png)

This would be optional setting.

**Comment by deulos** [comment]
I thought about it and updated the code to be classed inside .vue-flux instead of scoped, so will only inherit the styles when they are placed inside the component and will be easier to overwrite.

This way you can place the flux-index component outside and give it any appearance you need having the same functionality. This means, vertical, horizontal, aligned any side, with arrows or with scrolls.

If you agree with this latest changes will release it this afternoon finally :)

**Comment by BorysTyminski** [comment]
Sure sounds great.

**Comment by BorysTyminski** [comment]
Remember to keep wiki's up to date when you release `3.0.0` as it's most important thing for other devs.

**Comment by deulos** [comment]
Wiki should be updated now. Let me know if something missing :)
